//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaderBoardService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerScore
    {
        public int id { get; set; }
        public string username { get; set; }
        public int rank { get; set; }
        public int kills { get; set; }
        public int score { get; set; }
        public System.DateTime timestamp { get; set; }
        public string matchname { get; set; }
    
        public virtual User User { get; set; }
    }
}
